"""Complete exercise database with Beginner, Intermediate, and Expert difficulty levels."""

EXERCISES: dict[str, list[dict]] = {
    # ===== CHEST =====
    "chest": [
        {
            "name": "Flat Barbell Bench Press",
            "muscles": ["Chest", "Triceps", "Shoulders"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "rT7DgCr-3pg",
            "tips": [
                "Keep your feet flat on the floor and back arched slightly",
                "Lower the bar to mid-chest, not your neck",
                "Push through your chest, not just your arms",
                "Keep wrists straight and grip firm",
                "Use a spotter when going heavy",
            ],
        },
        {
            "name": "Dumbbell Bench Press",
            "muscles": ["Chest", "Triceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "VmB1G1K7v94",
            "tips": [
                "Keep dumbbells in line with your mid-chest",
                "Lower until upper arms are parallel to the floor",
                "Press up in a slight arc, bringing dumbbells together at top",
                "Keep your shoulder blades pinched together",
            ],
        },
        {
            "name": "Incline Dumbbell Press",
            "muscles": ["Upper Chest", "Shoulders"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "8iPEnn-ltC8",
            "tips": [
                "Set bench to 30-45 degree incline",
                "Don't flare elbows out too wide",
                "Control the weight on the way down",
                "Focus on squeezing chest at the top",
            ],
        },
        {
            "name": "Push-Ups",
            "muscles": ["Chest", "Triceps", "Core"],
            "sets": 3,
            "reps": "10-15",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "IODxDxX7oi4",
            "tips": [
                "Keep your body in a straight line from head to heels",
                "Lower until chest nearly touches the floor",
                "Keep core engaged throughout the movement",
                "Start with knee push-ups if needed",
            ],
        },
        {
            "name": "Wide Push-Ups",
            "muscles": ["Chest", "Shoulders"],
            "sets": 3,
            "reps": "10-15",
            "equipment": ["bodyweight"],
            "youtube_id": "pfMYnMgRFCQ",
            "tips": [
                "Place hands wider than shoulder width",
                "Focus on stretching the chest at the bottom",
                "Keep core tight and body straight",
                "Slower tempo for more chest activation",
            ],
        },
        {
            "name": "Decline Push-Ups",
            "muscles": ["Upper Chest", "Shoulders", "Triceps"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["bodyweight"],
            "youtube_id": "SKPab2YC8BE",
            "tips": [
                "Place feet on a chair or bench",
                "Hands shoulder-width apart on the floor",
                "Lower chest toward the floor",
                "Targets upper chest more than regular push-ups",
            ],
        },
        {
            "name": "Cable Chest Fly",
            "muscles": ["Chest"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["full-gym"],
            "youtube_id": "Iwe6AmxVf7o",
            "tips": [
                "Keep a slight bend in your elbows throughout",
                "Squeeze your chest at the peak contraction",
                "Control the weight - don't let cables pull you back",
                "Keep shoulder blades retracted",
            ],
        },
        {
            "name": "Chest Dips (Assisted if needed)",
            "muscles": ["Chest", "Triceps", "Shoulders"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["full-gym"],
            "youtube_id": "wjUmnZH528Y",
            "tips": [
                "Lean forward to target chest more",
                "Lower until upper arms are parallel to the floor",
                "Use the assisted dip machine if bodyweight is too hard",
                "Keep elbows slightly flared",
            ],
        },
        {
            "name": "Barbell Incline Press",
            "muscles": ["Upper Chest", "Triceps", "Shoulders"],
            "sets": 4,
            "reps": "8-10",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "DbFgADa2PL8",
            "tips": [
                "Set bench to 30 degrees for best upper chest activation",
                "Lower bar to upper chest",
                "Drive feet into the floor for stability",
                "Use a controlled tempo",
            ],
        },
        {
            "name": "Weighted Dips",
            "muscles": ["Chest", "Triceps", "Shoulders"],
            "sets": 4,
            "reps": "8-10",
            "equipment": ["full-gym"],
            "difficulty": "expert",
            "youtube_id": "2z8JmcrW-As",
            "tips": [
                "Use a dip belt or hold a dumbbell between your feet",
                "Lean forward to emphasize chest",
                "Full range of motion is key",
                "Only add weight once bodyweight dips are easy for 15+ reps",
            ],
        },
        {
            "name": "Dumbbell Fly",
            "muscles": ["Chest"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "difficulty": "intermediate",
            "youtube_id": "eozdVDA78K0",
            "tips": [
                "Keep a slight bend in elbows throughout",
                "Lower until you feel a stretch in your chest",
                "Squeeze chest muscles at the top",
                "Don't go too heavy - this is an isolation exercise",
            ],
        },
        {
            "name": "Landmine Press",
            "muscles": ["Upper Chest", "Shoulders"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "bYjklCCfReo",
            "tips": [
                "Press at an angle to target upper chest",
                "Keep core braced throughout",
                "Control the eccentric portion",
                "Great alternative to overhead pressing",
            ],
        },
    ],

    # ===== BACK =====
    "back": [
        {
            "name": "Lat Pulldown",
            "muscles": ["Lats", "Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "youtube_id": "CAwf7n6Luuc",
            "tips": [
                "Grip slightly wider than shoulder width",
                "Pull the bar to your upper chest, not behind your neck",
                "Lean back slightly and squeeze your shoulder blades",
                "Control the weight on the way up",
            ],
        },
        {
            "name": "Seated Cable Row",
            "muscles": ["Back", "Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "youtube_id": "GZbfZ033f74",
            "tips": [
                "Sit upright with a slight lean forward at the start",
                "Pull to your lower chest/upper abdomen",
                "Squeeze shoulder blades together at the end",
                "Don't swing your torso back and forth",
            ],
        },
        {
            "name": "Bent-Over Dumbbell Row",
            "muscles": ["Back", "Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "roCP6wCXPqo",
            "tips": [
                "Keep your back flat, not rounded",
                "Pull the dumbbell toward your hip",
                "Squeeze your shoulder blade at the top",
                "Keep your core tight for spine support",
            ],
        },
        {
            "name": "Pull-Ups (or Assisted)",
            "muscles": ["Lats", "Biceps", "Core"],
            "sets": 3,
            "reps": "5-10",
            "equipment": ["full-gym", "bodyweight"],
            "youtube_id": "eGo4IYlbE5g",
            "tips": [
                "Use an overhand grip, slightly wider than shoulders",
                "Pull until chin is above the bar",
                "Use assisted pull-up machine or resistance bands if needed",
                "Avoid swinging - use controlled movement",
            ],
        },
        {
            "name": "Inverted Rows",
            "muscles": ["Back", "Biceps", "Core"],
            "sets": 3,
            "reps": "10-15",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "dYqNbUjpMS4",
            "tips": [
                "Keep body straight from head to heels",
                "Pull chest to the bar",
                "Squeeze shoulder blades together at the top",
                "Adjust difficulty by changing foot position",
            ],
        },
        {
            "name": "Face Pulls",
            "muscles": ["Rear Delts", "Upper Back"],
            "sets": 3,
            "reps": "15-20",
            "equipment": ["full-gym"],
            "youtube_id": "rep-qVOkqgk",
            "tips": [
                "Set cable at face height",
                "Pull toward your forehead, separating the rope ends",
                "Externally rotate your shoulders at the end",
                "Keep elbows high throughout",
            ],
        },
        {
            "name": "Barbell Bent-Over Row",
            "muscles": ["Back", "Biceps", "Core"],
            "sets": 4,
            "reps": "8-10",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "FWJR5Ve8bnQ",
            "tips": [
                "Hinge at hips with flat back",
                "Pull bar to lower chest",
                "Squeeze shoulder blades at the top",
                "Keep core tight throughout",
            ],
        },
        {
            "name": "Weighted Pull-Ups",
            "muscles": ["Lats", "Biceps", "Core"],
            "sets": 4,
            "reps": "6-8",
            "equipment": ["full-gym"],
            "difficulty": "expert",
            "youtube_id": "ua9-MjKaEMk",
            "tips": [
                "Use a dip belt or hold dumbbell between feet",
                "Full range of motion - dead hang to chin over bar",
                "Control the negative for maximum growth",
                "Only add weight once you can do 12+ bodyweight pull-ups",
            ],
        },
        {
            "name": "T-Bar Row",
            "muscles": ["Back", "Biceps", "Core"],
            "sets": 4,
            "reps": "8-10",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "j3Igk5nyZE4",
            "tips": [
                "Keep back flat and hinge at hips",
                "Pull to your chest with elbows close to body",
                "Squeeze the back muscles at the top",
                "Use a close grip for more lat engagement",
            ],
        },
        {
            "name": "Pendlay Row",
            "muscles": ["Back", "Lats", "Core"],
            "sets": 4,
            "reps": "5-8",
            "equipment": ["full-gym"],
            "difficulty": "expert",
            "youtube_id": "ZlRrIsoDpKg",
            "tips": [
                "Bar starts on the floor each rep",
                "Explosive pull to lower chest",
                "Back parallel to floor throughout",
                "Great for building explosive back strength",
            ],
        },
    ],

    # ===== SHOULDERS =====
    "shoulders": [
        {
            "name": "Dumbbell Shoulder Press",
            "muscles": ["Shoulders", "Triceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "qEwKCR5JCog",
            "tips": [
                "Press directly overhead, not forward",
                "Don't lock out elbows completely at the top",
                "Keep core braced and avoid arching your back",
                "Lower until elbows are at 90 degrees",
            ],
        },
        {
            "name": "Lateral Raises",
            "muscles": ["Side Delts"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "3VcKaXpzqRo",
            "tips": [
                "Lead with your elbows, not your hands",
                "Lift to shoulder height, no higher",
                "Use light weight - this is an isolation exercise",
                "Keep a slight bend in your elbows",
            ],
        },
        {
            "name": "Front Raises",
            "muscles": ["Front Delts"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "-t7fuZ0KhDA",
            "tips": [
                "Raise to eye level, not overhead",
                "Alternate arms or use both together",
                "Keep a slight bend in elbows",
                "Control the negative - don't let gravity do the work",
            ],
        },
        {
            "name": "Pike Push-Ups",
            "muscles": ["Shoulders", "Triceps"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["bodyweight"],
            "youtube_id": "sposDXWEB0A",
            "tips": [
                "Form an inverted V with your body",
                "Lower your head toward the floor between your hands",
                "Push back up through your shoulders",
                "Elevate feet on a bench for more difficulty",
            ],
        },
        {
            "name": "Bodyweight Lateral Raise (Wall Slide)",
            "muscles": ["Side Delts", "Upper Back"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["bodyweight"],
            "youtube_id": "d2IG6fNuT0Y",
            "tips": [
                "Stand with back against a wall",
                "Slide arms up in a Y-shape",
                "Squeeze shoulder blades together",
                "Great for shoulder mobility and strength",
            ],
        },
        {
            "name": "Arm Circles",
            "muscles": ["Shoulders"],
            "sets": 3,
            "reps": "20 each direction",
            "equipment": ["bodyweight"],
            "youtube_id": "bO8ISmzXkfE",
            "tips": [
                "Extend arms straight out to the sides",
                "Make small circles, gradually increase size",
                "Reverse direction halfway through",
                "Keep core engaged throughout",
            ],
        },
        {
            "name": "Arnold Press",
            "muscles": ["Shoulders", "Triceps"],
            "sets": 4,
            "reps": "8-10",
            "equipment": ["full-gym", "basic"],
            "difficulty": "intermediate",
            "youtube_id": "6Z15_WdXmVw",
            "tips": [
                "Start with palms facing you at shoulder level",
                "Rotate palms outward as you press up",
                "Combines front raise and press in one movement",
                "Use moderate weight to maintain control",
            ],
        },
        {
            "name": "Handstand Push-Ups (Wall-Supported)",
            "muscles": ["Shoulders", "Triceps", "Core"],
            "sets": 3,
            "reps": "5-8",
            "equipment": ["bodyweight"],
            "difficulty": "expert",
            "youtube_id": "sOISmZafWjQ",
            "tips": [
                "Kick up against a wall for support",
                "Lower head toward the floor between hands",
                "Push back up through shoulders",
                "Build up to freestanding over time",
            ],
        },
        {
            "name": "Reverse Fly (Rear Delt Fly)",
            "muscles": ["Rear Delts", "Upper Back"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["full-gym", "basic"],
            "difficulty": "intermediate",
            "youtube_id": "EA7u4Q_8HQ0",
            "tips": [
                "Bend forward at hips with flat back",
                "Raise arms out to the sides",
                "Squeeze shoulder blades at the top",
                "Use lighter weight for proper form",
            ],
        },
        {
            "name": "Barbell Overhead Press",
            "muscles": ["Shoulders", "Triceps", "Core"],
            "sets": 4,
            "reps": "6-8",
            "equipment": ["full-gym"],
            "difficulty": "expert",
            "youtube_id": "2yjwXTZQDDI",
            "tips": [
                "Start with bar at collarbone level",
                "Press straight overhead, moving head back slightly",
                "Lock out at the top",
                "Keep core extremely tight to protect lower back",
            ],
        },
    ],

    # ===== LEGS =====
    "legs": [
        {
            "name": "Barbell Back Squat",
            "muscles": ["Quads", "Glutes", "Hamstrings"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["full-gym"],
            "youtube_id": "ultWZbUMPL8",
            "tips": [
                "Keep feet shoulder-width apart, toes slightly out",
                "Squat to at least parallel (thighs parallel to floor)",
                "Keep your chest up and back straight",
                "Push through your whole foot, not just toes",
                "Start with just the barbell to learn proper form",
            ],
        },
        {
            "name": "Goblet Squat",
            "muscles": ["Quads", "Glutes"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "MeIiIdhvXT4",
            "tips": [
                "Hold dumbbell close to your chest",
                "Keep elbows pointing down between your knees",
                "Sit back and down as if into a chair",
                "Great exercise to learn squat form",
            ],
        },
        {
            "name": "Leg Press",
            "muscles": ["Quads", "Glutes"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "youtube_id": "IZxyjW7MPJQ",
            "tips": [
                "Place feet shoulder-width on the platform",
                "Don't lock knees at the top",
                "Lower until knees are at 90 degrees",
                "Keep your lower back pressed against the pad",
            ],
        },
        {
            "name": "Romanian Deadlift (Dumbbell)",
            "muscles": ["Hamstrings", "Glutes", "Lower Back"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "7j-2w4-P14I",
            "tips": [
                "Keep dumbbells close to your legs throughout",
                "Hinge at your hips, pushing them back",
                "Keep a slight bend in your knees",
                "Feel the stretch in your hamstrings",
                "Keep your back flat - don't round",
            ],
        },
        {
            "name": "Walking Lunges",
            "muscles": ["Quads", "Glutes", "Hamstrings"],
            "sets": 3,
            "reps": "12 each leg",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "L8fvypPH3SA",
            "tips": [
                "Take a long stride forward",
                "Lower back knee toward the floor",
                "Keep front knee over your ankle, not past toes",
                "Push through front heel to step forward",
            ],
        },
        {
            "name": "Bodyweight Squats",
            "muscles": ["Quads", "Glutes"],
            "sets": 3,
            "reps": "15-20",
            "equipment": ["bodyweight"],
            "youtube_id": "aclHkVaku9U",
            "tips": [
                "Keep weight on your heels",
                "Arms out front for balance",
                "Go as deep as comfortable while maintaining form",
                "Squeeze glutes at the top",
            ],
        },
        {
            "name": "Leg Curl Machine",
            "muscles": ["Hamstrings"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "youtube_id": "1Tq3QdYUuHs",
            "tips": [
                "Adjust the pad to sit just above your ankles",
                "Curl slowly and squeeze at the peak",
                "Don't let the weight slam down",
                "Keep hips pressed against the pad",
            ],
        },
        {
            "name": "Calf Raises",
            "muscles": ["Calves"],
            "sets": 3,
            "reps": "15-20",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "gwLzBJYoWlI",
            "tips": [
                "Rise up on your toes as high as possible",
                "Lower slowly for a full stretch",
                "Hold at the top for 1 second",
                "Can be done on a step for greater range of motion",
            ],
        },
        {
            "name": "Bulgarian Split Squat",
            "muscles": ["Quads", "Glutes", "Hamstrings"],
            "sets": 3,
            "reps": "10-12 each leg",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "difficulty": "intermediate",
            "youtube_id": "2C-uNgKwPLE",
            "tips": [
                "Place rear foot on a bench behind you",
                "Lower until front thigh is parallel to floor",
                "Keep torso upright and core tight",
                "Push through front heel to stand",
            ],
        },
        {
            "name": "Barbell Front Squat",
            "muscles": ["Quads", "Core", "Glutes"],
            "sets": 4,
            "reps": "6-8",
            "equipment": ["full-gym"],
            "difficulty": "expert",
            "youtube_id": "m4ytaCJZpl0",
            "tips": [
                "Rest bar on front deltoids with elbows high",
                "Requires good wrist and shoulder mobility",
                "Go deep - below parallel if possible",
                "Targets quads more than back squat",
            ],
        },
        {
            "name": "Pistol Squats (Single Leg)",
            "muscles": ["Quads", "Glutes", "Balance"],
            "sets": 3,
            "reps": "5-8 each leg",
            "equipment": ["bodyweight"],
            "difficulty": "expert",
            "youtube_id": "qDcniqddTeE",
            "tips": [
                "Stand on one leg, extend the other in front",
                "Squat down as deep as possible",
                "Use a chair or doorframe for balance if needed",
                "Ultimate bodyweight leg exercise",
            ],
        },
        {
            "name": "Leg Extension Machine",
            "muscles": ["Quads"],
            "sets": 3,
            "reps": "12-15",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "YyvSfVjQeL0",
            "tips": [
                "Extend legs fully at the top",
                "Squeeze quads at peak contraction",
                "Lower slowly under control",
                "Adjust pad to sit just above ankles",
            ],
        },
        {
            "name": "Barbell Hip Thrust",
            "muscles": ["Glutes", "Hamstrings"],
            "sets": 4,
            "reps": "8-12",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "SEdqd1n0icg",
            "tips": [
                "Place upper back on a bench",
                "Roll barbell over hips with a pad",
                "Drive hips up squeezing glutes at the top",
                "Chin slightly tucked, don't hyperextend neck",
            ],
        },
    ],

    # ===== ARMS =====
    "arms": [
        {
            "name": "Barbell Bicep Curl",
            "muscles": ["Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "youtube_id": "kwG2ipFRgFo",
            "tips": [
                "Keep elbows pinned to your sides",
                "Don't swing your body to lift the weight",
                "Squeeze biceps at the top",
                "Lower slowly - control the negative",
            ],
        },
        {
            "name": "Dumbbell Bicep Curl",
            "muscles": ["Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "ykJmrZ5v0Oo",
            "tips": [
                "Alternate arms or curl both simultaneously",
                "Keep upper arms stationary",
                "Supinate (rotate) wrists as you curl up",
                "Full extension at the bottom",
            ],
        },
        {
            "name": "Hammer Curls",
            "muscles": ["Biceps", "Forearms"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "zC3nLlEvin4",
            "tips": [
                "Keep palms facing each other throughout",
                "Don't swing - use strict form",
                "Great for forearm development too",
                "Squeeze at the top",
            ],
        },
        {
            "name": "Tricep Pushdown (Cable)",
            "muscles": ["Triceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "youtube_id": "2-LAMcpzODU",
            "tips": [
                "Keep elbows pinned to your sides",
                "Push down until arms are fully extended",
                "Don't lean forward excessively",
                "Control the weight back up",
            ],
        },
        {
            "name": "Overhead Tricep Extension",
            "muscles": ["Triceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "youtube_id": "_gsUck-7M74",
            "tips": [
                "Keep upper arms close to your ears",
                "Lower the weight behind your head slowly",
                "Extend fully at the top",
                "Keep core braced to protect your back",
            ],
        },
        {
            "name": "Diamond Push-Ups",
            "muscles": ["Triceps", "Chest"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["bodyweight"],
            "youtube_id": "J0DnG1_S3lg",
            "tips": [
                "Place hands close together forming a diamond shape",
                "Keep elbows close to your body",
                "Lower chest to your hands",
                "Great bodyweight tricep exercise",
            ],
        },
        {
            "name": "Bench Dips",
            "muscles": ["Triceps", "Shoulders"],
            "sets": 3,
            "reps": "10-15",
            "equipment": ["bodyweight"],
            "youtube_id": "0326dy_-CzM",
            "tips": [
                "Place hands on a chair or bench behind you",
                "Lower body by bending elbows to 90 degrees",
                "Push back up through your palms",
                "Keep back close to the bench",
            ],
        },
        {
            "name": "Chin-Ups (or Negative Chin-Ups)",
            "muscles": ["Biceps", "Lats"],
            "sets": 3,
            "reps": "5-10",
            "equipment": ["bodyweight"],
            "youtube_id": "brhRXlOhsAM",
            "tips": [
                "Use an underhand (supinated) grip",
                "Pull chin above the bar",
                "If too hard, jump up and lower slowly (negatives)",
                "Great bodyweight biceps builder",
            ],
        },
        {
            "name": "Preacher Curl",
            "muscles": ["Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "fIWP-FRFNU0",
            "tips": [
                "Use the preacher bench to isolate biceps",
                "Lower fully for a complete stretch",
                "Don't swing - strict form only",
                "Great for building the bicep peak",
            ],
        },
        {
            "name": "Close-Grip Bench Press",
            "muscles": ["Triceps", "Chest"],
            "sets": 4,
            "reps": "8-10",
            "equipment": ["full-gym"],
            "difficulty": "expert",
            "youtube_id": "nEF0bv2FW94",
            "tips": [
                "Grip bar with hands shoulder-width apart",
                "Keep elbows tucked close to your body",
                "Lower to lower chest and press back up",
                "Heavy compound movement for triceps",
            ],
        },
        {
            "name": "Skull Crushers (Lying Tricep Extension)",
            "muscles": ["Triceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "difficulty": "intermediate",
            "youtube_id": "d_KZxkY_0cM",
            "tips": [
                "Lie on a bench and hold barbell/dumbbells above chest",
                "Lower weight toward forehead by bending elbows",
                "Keep upper arms stationary",
                "Extend back to starting position",
            ],
        },
        {
            "name": "Concentration Curl",
            "muscles": ["Biceps"],
            "sets": 3,
            "reps": "10-12",
            "equipment": ["full-gym", "basic"],
            "difficulty": "intermediate",
            "youtube_id": "0AUGkch3tzc",
            "tips": [
                "Sit on bench, rest elbow on inner thigh",
                "Curl with full range of motion",
                "Squeeze bicep hard at the top",
                "Great for mind-muscle connection",
            ],
        },
    ],

    # ===== CORE =====
    "core": [
        {
            "name": "Plank",
            "muscles": ["Core", "Shoulders"],
            "sets": 3,
            "reps": "30-60 sec",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "ASdvN_XEl_c",
            "tips": [
                "Keep body in a straight line",
                "Don't let hips sag or pike up",
                "Breathe normally throughout",
                "Start with shorter holds and build up",
            ],
        },
        {
            "name": "Dead Bug",
            "muscles": ["Core"],
            "sets": 3,
            "reps": "10 each side",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "4XLEnwUr1d8",
            "tips": [
                "Keep lower back pressed into the floor",
                "Move opposite arm and leg simultaneously",
                "Breathe out as you extend",
                "Go slowly for maximum benefit",
            ],
        },
        {
            "name": "Cable Woodchop",
            "muscles": ["Core", "Obliques"],
            "sets": 3,
            "reps": "12 each side",
            "equipment": ["full-gym"],
            "youtube_id": "pAplQXk3dkU",
            "tips": [
                "Rotate through your torso, not your arms",
                "Keep arms relatively straight",
                "Control the movement in both directions",
                "Feet shoulder-width apart",
            ],
        },
        {
            "name": "Bicycle Crunches",
            "muscles": ["Core", "Obliques"],
            "sets": 3,
            "reps": "15 each side",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "9FGilxCbdz8",
            "tips": [
                "Touch elbow to opposite knee",
                "Extend the other leg fully",
                "Don't pull on your neck",
                "Go slow for better muscle activation",
            ],
        },
        {
            "name": "Hanging Knee Raise",
            "muscles": ["Lower Abs", "Hip Flexors"],
            "sets": 3,
            "reps": "10-15",
            "equipment": ["full-gym"],
            "youtube_id": "Pr1ieGZ5atk",
            "tips": [
                "Hang from a pull-up bar with arms extended",
                "Raise knees toward chest",
                "Don't swing - control the movement",
                "Use ab straps if grip is limiting",
            ],
        },
        {
            "name": "Mountain Climbers",
            "muscles": ["Core", "Shoulders", "Cardio"],
            "sets": 3,
            "reps": "20 each side",
            "equipment": ["full-gym", "basic", "bodyweight"],
            "youtube_id": "nmwgirgXLYM",
            "tips": [
                "Keep hips level - don't bounce them up",
                "Drive knees toward chest alternately",
                "Keep hands directly under shoulders",
                "Start slow and increase speed",
            ],
        },
        {
            "name": "Ab Wheel Rollout",
            "muscles": ["Core", "Shoulders"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["full-gym", "basic"],
            "difficulty": "intermediate",
            "youtube_id": "rqiTPi0eOCg",
            "tips": [
                "Start on knees with wheel in front of you",
                "Roll forward keeping core extremely tight",
                "Don't let lower back arch",
                "Roll back using your abs, not your arms",
            ],
        },
        {
            "name": "Dragon Flags",
            "muscles": ["Core", "Hip Flexors"],
            "sets": 3,
            "reps": "5-8",
            "equipment": ["full-gym", "bodyweight"],
            "difficulty": "expert",
            "youtube_id": "moyFIvRrS0s",
            "tips": [
                "Lie on a bench and grip behind your head",
                "Lift entire body up keeping it straight",
                "Lower slowly without touching the bench",
                "Bruce Lee's famous core exercise - extremely challenging",
            ],
        },
        {
            "name": "L-Sit Hold",
            "muscles": ["Core", "Hip Flexors", "Triceps"],
            "sets": 3,
            "reps": "15-30 sec",
            "equipment": ["bodyweight"],
            "difficulty": "expert",
            "youtube_id": "IUZJoSP66HI",
            "tips": [
                "Sit on floor with legs extended, hands by hips",
                "Press down and lift entire body off the floor",
                "Keep legs straight and parallel to ground",
                "Start with tucked knees if full L-sit is too hard",
            ],
        },
        {
            "name": "Pallof Press",
            "muscles": ["Core", "Obliques"],
            "sets": 3,
            "reps": "10-12 each side",
            "equipment": ["full-gym"],
            "difficulty": "intermediate",
            "youtube_id": "AH_QZLm_0-s",
            "tips": [
                "Stand perpendicular to cable machine",
                "Press cable away from chest and hold",
                "Resist rotation - this is an anti-rotation exercise",
                "Keep core braced throughout",
            ],
        },
        {
            "name": "Hanging Leg Raise (Straight Legs)",
            "muscles": ["Lower Abs", "Hip Flexors", "Core"],
            "sets": 3,
            "reps": "8-12",
            "equipment": ["full-gym", "bodyweight"],
            "difficulty": "expert",
            "youtube_id": "hdng3Nm1x_E",
            "tips": [
                "Hang from bar with legs fully extended",
                "Raise straight legs to parallel or higher",
                "Control the descent - no swinging",
                "Advanced progression from hanging knee raises",
            ],
        },
    ],
}
